/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Challenges": "挑战",
    "Close": "关闭",
    "Costs": "成本",
    "Welcome back!": "欢迎回来！",
    "You were gone for": "你离开了 ",
    "Next at": "下一个在 ",
    "Normal": "正常",
    "Unlock buy max for A upgrades": "解锁 A 升级的购买最大",
    "Unlock a new A upgrade": "解锁一个新的 A 升级",
    "Unlock a new B upgrade": "解锁一个新的 B 升级",
    "Reset all A content for": "重置所有 A 内容得到",
    "Producing": "产生",
    "Notation and analysis are based on": "符号和分析基于",
    "Keep B upgrades 2 and 3 on C reset": "在 C 重置时保留 B 升级 2 和 3",
    "Finish challenge": "完成挑战",
    "Export game": "导出存档",
    "Reset all A-B content for": "重置所有 A-B 内容得到",
    "A Challenges": "A 挑战",
    "Array Game": "数组游戏",
    "A-boosterator production is stronger": "A-助推器生产更强",
    "A-boosterators, giving you": "A-助推器，给你",
    "C generators": "C 生成器",
    "A generators": "B 生成器",
    "B generators": "B 生成器",
    "B generators bought multiply their corresponding A generator's production": "购买的 B 生成器乘以其相应的 A 生成器的产量",
    "B, multiplying A gain by": "B，将A增益乘以",
    "Bird's Array Notation": "鸟阵表示法",
    "Buy max": "购买最大",
    "Buying generators beyond 20 increases that generator's production": "购买 20 个以上的生成器会增加该生成器的产量",
    "C amount multiplies B generator production": "C 数量乘以 B 生成器产量",
    "C-4s bought multiply C gain": "已购买的 C-4s 乘以 C 增益",
    "C, multiplying A and B gain by": "C，将A和B增益乘以",
    "Hard reset": "硬重置",
    "On": "开",
    "Keep all B upgrades on C reset": "在 C 重置时保留所有 B 升级",
    "Multiply B generator production by 100": "将 B 生成器产量乘以 100",
    "A-boosters": "A-助推器",
    "A-boosters per second": "A-助推器 每秒",
    "A-boosters, boosting A generator production by *": "A 助推器，将 A 生成器的产量提高 *",
    "A-boosterators multiply A generator production": "A 助推器乘以 A 生成器产量",
    "Automatically buy A generators (outside of Ch-A1)": "自动购买 A 生成器（除了 挑战-A1）",
    "Automatically buy A upgrades": "自动购买 A 升级",
    "Automatically gain 20% of B reset amount per second": "每秒自动获得20%的 B 重置量",
    "Automatically gain 20% of C reset amount per second": "每秒自动获得20%的 C 重置量",
    "B-1s bought multiply A-booster gain": "已购买的 B-1s 乘以 A-助推器 增益",
    "C milestones": "C 里程碑",
    "Entering/leaving these challenges resets all A content. Challenge completions are kept on B and C resets.": "进入/离开这些挑战会重置所有 A 内容。 挑战完成保留在 B 和 C 重置时。",
    "Formula for the A generator amount boost is improved": "A 生成器数量提升公式已改进",
    "Formula for the B generator amount boost is improved": "B 生成器数量提升公式已改进",
    "If your B is ever reduced to 0, it will automatically increase to 1": "如果你的 B 曾经减少到 0，它会自动增加到 1",
    "If your C is ever reduced to 0, it will automatically increase to 1": "如果你的 C 曾经减少到 0，它会自动增加到 1",
    "Requires 20 B (Will not reduce B)": "需要 20 B（不会减少 B）",
    "Reward: B gain is increased based on B-5 amount (*": "奖励：B收益根据B-5数量增加（*",
    "Reward: C gain is increased (*": "奖励：C增益增加（*",
    "A generator production is ^0.2.": "A 生成器 产量为 ^0.2。",
    "A-1 production is ^0.5. You cannot buy A generators.": "A-1 产量为 ^0.5。 您不能购买 A 生成器。",
    "A-2 amount divides A-2 production.": "A-2 的数量除以 A-2 的产量。",
    "A-3 cannot be bought or produced.": "无法购买或生产 A-3。",
    "A and B generator production is ^0.1.": "A 和 B 生成器产量为 ^0.1。",
    "A generator amount boost formula is improved again": "再次改进发电量提升公式",
    "All A and B generator production is divided by 1e35.": "所有 A 和 B 生成器的产量除以 1e35。",
    "Automatically buy B generators": "自动购买B生成器",
    "Automatically buy B upgrades and A-boosterators": "自动购买 B 升级和 A 助推器",
    "Automatically gain 20% of D reset amount per second": "每秒自动获得20%的D重置量",
    "B Challenges": "B 挑战",
    "B generators and A-boosters cannot be produced, but B generators can be bought.": "无法生产 B 生成器和 A 助推器，但可以购买 B 生成器。",
    "B per second": "B每秒",
    "B-1 production is 0. C-1 now produces A-5. A-1 production is ^0.5.": "B-1 产量为 0。C-1 现在生产 A-5。 A-1 产量为 ^0.5。",
    "C generators multiply their corresponding B generator's production": "C 生成器乘以其对应的 B 生成器的产量",
    "D gain is squared": "D增益平方",
    "D generators": "D 生成器",
    "D milestones": "D 里程碑",
    "D-1s bought multiply C gain": "D-1s 购买乘以 C 增益",
    "D-5 amount multiplies C generator production": "D-5 数量乘以 C 生成器产量",
    "D, multiplying A, B and C gain by": "D、A、B、C增益乘以",
    "Entering/leaving these challenges resets all A-B content. Challenge completions are kept on C and D resets.": "进入/离开这些挑战会重置所有 A-B 内容。 挑战完成保持在 C 和 D 重置。",
    "Formula for the C generator amount boost is improved": "改进了C生成器量提升公式",
    "If your D is ever reduced to 0, it will automatically increase to 1": "如果你的 D 曾经减少到 0，它会自动增加到 1",
    "Keep A challenges permanently": "永久保留A挑战",
    "Keep all B upgrades permanently": "永久保留所有 B 升级",
    "Keep C milestones on D reset": "在 D 重置时保持 C 里程碑",
    "Made by Demonin": "由 Demonin 制作",
    "Max all": "最大所有",
    "Monospace": "等宽",
    "Off": "离开",
    "Pixelated": "像素化",
    "Reset all A-C content for": "重置所有 A-C 内容",
    "Reward: B gain is increased (*": "奖励：B增益增加（*",
    "You are gaining": "你正在获得",
    "Distribute SP equally": "平均分配SP",
    "E, multiplying A and D gain by": "E，将A和D增益乘以",
    "(Gaining E will not spend your SP)": "（获得E不会花费你的SP）",
    "] separator": "] 分隔符",
    "A amount multiplies separator and SP gain (currently *": "数量乘以分隔符和 SP 增益（目前 *",
    "Array items II": "数组项 II",
    "Automatically gain 100% of separators and SP reset amount per second": "每秒自动获得 100% 的分隔符和 SP 重置量",
    "Boost SP-B": "提升SP-B",
    "Boost SP-Ch": "提升SP-Ch",
    "Boost SP-D": "提升SP-D",
    "Boosting B gain by ^": "将 B 增益提高 ^",
    "Boosting Ch-A1 and Ch-B1 effect by ^": "通过 ^ 提升 Ch-A1 和 Ch-B1 效应",
    "Boosting D gain by *": "将 D 增益提高 *",
    "Gain 1 E": "获得 1 E",
    "Gain 1 F": "获得 1 F",
    "Gain max": "获得最大",
    "Keep 1 C and C milestones on separator reset": "在分隔符重置时保留 1 个 C 和 C 里程碑",
    "Keep 1 D and C milestones on separator reset": "在分隔符重置时保留 1 个 D 和 C 里程碑",
    "Keep A and B challenges permanently": "永久保留 A 和 B 挑战",
    "Keep A challenges on B-D resets": "在 B-D 重置时保持 A 挑战",
    "Keep B upgrades on separator reset": "在分隔符重置时保持 B 升级",
    "Next: *": "下一个： *",
    "Next: ^": "下一个：^",
    "Refund SP from boosts and upgrades": "从提升和升级中退还 SP",
    "Requires": "要求",
    "Reset all A-D content to upgrade to a [": "重置所有 A-D 内容以升级到 [",
    "separators": "分隔符",
    "Separators": "分隔符",
    "SP on reset": "SP 在重置时",
    "Spend max": "消费上限",
    "total SP": "总SP",
    "total)": "总计）",
    "Unlock": "解锁",
    "unspent separator points (": "未使用的分隔点数 (",
    "Will perform a separator reset!": "将执行分隔重置！",
    "You have a [": "你有一个 [",
    "You will gain": "你将获得",
    "D per second": "D 每秒",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Generator ": "生成器 ",
    "Confirmation: ": "确认：",
    "Number format: ": "数字格式：",
    "Array item ": "数组项 ",
    "Font: ": "字体：",
    "Import game": "导入存档",
    "Unlock Ch-": "解锁 挑战-",
    "Array game v": "数组游戏 v",
    "F, multiplying separator and SP gain by": "F，将分隔符和SP增益乘以",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^数组(.+)$/,
    /^生成(.+)$/,
    /^购买(.+)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^e([\d\.,]+)$/,
    /^([\d\.,]+) C$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Buy a (.+)$/, '购买1个 $1'],
    [/^Buy an A-boosterator$/, '购买1个 A-助推器'],
    [/^Buy an (.+)$/, '购买1个 $1'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) hours$/, '$1 小时'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) SP spent$/, '$1 花费的 SP'],
    [/^Double A\-([\d\.,]+) production \(Currently \*$/, '双倍 A\-$1 生产（当前\*'],
    [/^Triple (.+) gain \(Currently \*$/, '三倍 $1 增益（当前\*'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Costs (.+) B$/, '成本 $1 B'],
    [/^Costs (.+) SP$/, '成本 $1 SP'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Reward: (.+) production is increased \(\*$/, '奖励：$1 产量增加（\*'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);